server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: random-user
  boot:
    admin:
      client:
        url: http://127.0.0.1:8090/admin
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    env:
      show-values: always
  tracing:
    sampling:
      probability: 1.0

random-user:
  url: https://randomuser.me/api/

logging:
  level:
    web: info
    com:
      github:
        randomuser:
          prediction: info
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 90
      total-size-cap: 20GB
  file:
    name: logs/${spring.application.name}.log

http-exchange-repository-capacity: 1000

springdoc:
  swagger-ui:
    path: /api/random-user/swagger-ui.html